2024-12-12 16:43 - INFO - starting server
2024-12-12 16:45 - INFO - starting server
2024-12-12 16:45 - INFO - start_recording
2024-12-12 16:45 - INFO - starting recording for test1.mp3
2024-12-12 16:45 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-12 16:45 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-12 16:45 - INFO - start_recording
2024-12-12 16:45 - INFO - starting recording for test2.mp3
2024-12-12 16:45 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-12 16:45 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-12 16:46 - INFO - start_recording
2024-12-12 16:46 - INFO - starting recording for test3.mp3
2024-12-12 16:46 - INFO - get_recordings
2024-12-12 16:46 - INFO - stop_recording
2024-12-12 16:46 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-12 16:46 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-12 18:01 - INFO - starting server
2024-12-12 18:01 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 144, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-12 18:01 - INFO - starting server
2024-12-12 18:01 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 144, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-12 18:01 - INFO - starting server
2024-12-12 18:01 - INFO - start_recording
2024-12-12 18:01 - INFO - starting recording for test1.mp3
2024-12-12 18:01 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-12 18:01 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-12 18:01 - INFO - start_recording
2024-12-12 18:01 - INFO - starting recording for test2.mp3
2024-12-12 18:01 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-12 18:01 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-12 18:01 - INFO - start_recording
2024-12-12 18:01 - INFO - starting recording for test3.mp3
2024-12-12 18:01 - INFO - get_recordings
2024-12-12 18:01 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-12 18:01 - INFO - stop_recording
2024-12-12 18:01 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-12 18:12 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 144, in main
    filename=ffr_config.SERVER_LOG_LOC,
KeyboardInterrupt
2024-12-12 18:12 - INFO - starting server
2024-12-12 18:12 - INFO - start_recording
2024-12-12 18:12 - INFO - starting recording for test1.mp3
2024-12-12 18:12 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-12 18:12 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-12 18:12 - INFO - start_recording
2024-12-12 18:12 - INFO - starting recording for test2.mp3
2024-12-12 18:12 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-12 18:12 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-12 18:12 - INFO - start_recording
2024-12-12 18:12 - INFO - starting recording for test3.mp3
2024-12-12 18:12 - INFO - get_recordings
2024-12-12 18:12 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-12 18:12 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-12 18:12 - INFO - starting server
2024-12-12 18:13 - INFO - start_recording
2024-12-12 18:13 - INFO - starting recording for test1.mp3
2024-12-12 18:13 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-12 18:13 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-12 18:13 - INFO - start_recording
2024-12-12 18:13 - INFO - starting recording for test2.mp3
2024-12-12 18:13 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-12 18:13 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-12 18:13 - INFO - start_recording
2024-12-12 18:13 - INFO - starting recording for test3.mp3
2024-12-12 18:13 - INFO - get_recordings
2024-12-12 18:13 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-12 18:13 - INFO - stop_recording
2024-12-12 18:13 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-12 18:19 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 156, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-13 05:11 - INFO - starting server
2024-12-13 05:12 - INFO - start_recording
2024-12-13 05:12 - INFO - starting recording for rockin.mp3
2024-12-13 05:12 - DEBUG - Starting new HTTPS connection (1): s4.radio.co:443
2024-12-13 05:12 - DEBUG - https://s4.radio.co:443 "GET /s0f3a44a66/listen HTTP/1.1" 200 None
2024-12-13 05:13 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 156, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-13 05:13 - INFO - starting server
2024-12-13 05:15 - INFO - start_recording
2024-12-13 05:15 - INFO - starting recording for rocking.mp3
2024-12-13 05:15 - DEBUG - Starting new HTTPS connection (1): s4.radio.co:443
2024-12-13 05:15 - DEBUG - https://s4.radio.co:443 "GET /s0f3a44a66/listen HTTP/1.1" 200 None
2024-12-13 05:22 - INFO - get_recordings
2024-12-13 05:23 - INFO - get_recordings
2024-12-13 05:23 - INFO - get_recordings
2024-12-13 05:25 - INFO - get_recordings
2024-12-13 05:25 - INFO - get_recordings
2024-12-13 05:25 - INFO - stop_recording
2024-12-13 05:26 - INFO - get_recordings
2024-12-13 05:28 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 156, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-13 18:59 - INFO - starting server
2024-12-13 19:00 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 150, in main
    stop_recording(data.get("id"))
KeyboardInterrupt
2024-12-13 19:00 - INFO - starting server
2024-12-13 20:12 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 132, in main
    try:
KeyboardInterrupt
2024-12-13 20:14 - INFO - starting server
2024-12-13 20:15 - INFO - start_recording
2024-12-13 20:15 - INFO - starting recording for rocker01.mp3
2024-12-13 20:15 - DEBUG - Starting new HTTPS connection (1): s4.radio.co:443
2024-12-13 20:15 - DEBUG - https://s4.radio.co:443 "GET /s0f3a44a66/listen HTTP/1.1" 200 None
2024-12-13 20:15 - INFO - get_recordings
2024-12-13 20:15 - INFO - stop_recording
2024-12-13 20:16 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 136, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-13 20:16 - INFO - starting server
2024-12-13 20:23 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 136, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-13 20:23 - INFO - starting server
2024-12-13 20:23 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 136, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-13 22:03 - INFO - starting server
2024-12-13 22:04 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 141, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-13 22:06 - INFO - starting server
2024-12-13 22:13 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 142, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-13 22:14 - INFO - starting server
2024-12-13 22:15 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 142, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-13 22:15 - INFO - starting server
2024-12-13 22:16 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 142, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-13 22:16 - INFO - starting server
2024-12-13 22:16 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 142, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-13 22:16 - INFO - starting server
2024-12-13 22:17 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 142, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-13 14:20 - INFO - starting server
2024-12-13 14:20 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 142, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-13 14:20 - INFO - starting server
2024-12-13 14:22 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 142, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-13 14:22 - INFO - starting server
2024-12-13 14:23 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 142, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-13 14:32 - INFO - starting server
2024-12-13 14:33 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 142, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-13 14:33 - INFO - starting server
2024-12-13 14:34 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 142, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-13 14:37 - INFO - starting server
2024-12-13 14:37 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 142, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-13 14:38 - INFO - starting server
2024-12-15 19:10 - INFO - starting server
2024-12-15 19:11 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 165, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-15 19:13 - INFO - starting server
2024-12-15 19:14 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 165, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-15 19:15 - INFO - starting server
2024-12-15 19:15 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 165, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-15 19:15 - INFO - starting server
2024-12-15 19:16 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 165, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-15 19:16 - INFO - starting server
2024-12-15 19:30 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 165, in main
KeyboardInterrupt
2024-12-15 19:39 - INFO - starting server
2024-12-15 20:30 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 137, in main
    logging.info(data.get("action"))
KeyboardInterrupt
2024-12-15 20:30 - INFO - starting server
2024-12-15 20:30 - INFO - start_recording
2024-12-15 20:30 - INFO - starting recording for test1.mp3
2024-12-15 20:32 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 135, in main
KeyboardInterrupt
2024-12-15 20:32 - INFO - starting server
2024-12-15 20:32 - INFO - start_recording
2024-12-15 20:32 - INFO - starting recording for test1.mp3
2024-12-15 20:33 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 139, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-15 20:34 - INFO - starting server
2024-12-15 20:34 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 139, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-15 20:35 - INFO - starting server
2024-12-15 20:36 - INFO - start_recording
2024-12-15 20:36 - INFO - starting recording for test1.mp3
2024-12-15 20:36 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 139, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-15 20:36 - INFO - starting server
2024-12-15 20:36 - INFO - start_recording
2024-12-15 20:36 - INFO - starting recording for test1.mp3
2024-12-15 20:37 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 139, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-15 20:38 - INFO - starting server
2024-12-15 20:39 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 142, in main
    logging.info(data.get("action"))
KeyboardInterrupt
2024-12-15 20:39 - INFO - starting server
2024-12-15 20:39 - INFO - start_recording
2024-12-15 20:39 - INFO - starting recording for test1.mp3
2024-12-15 20:41 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 140, in main
    while True:
KeyboardInterrupt
2024-12-15 20:41 - INFO - starting server
2024-12-15 20:41 - INFO - start_recording
2024-12-15 20:41 - INFO - starting recording for test1.mp3
2024-12-15 20:41 - INFO - start_recording
2024-12-15 20:41 - INFO - starting recording for test1.mp3
2024-12-15 20:41 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 142, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-15 20:41 - INFO - starting server
2024-12-15 20:41 - INFO - start_recording
2024-12-15 20:41 - INFO - starting recording for test1.mp3
2024-12-15 20:42 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 142, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-15 20:42 - INFO - starting server
2024-12-15 20:42 - INFO - start_recording
2024-12-15 20:42 - INFO - starting recording for test1.mp3
2024-12-15 20:42 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 142, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-15 20:43 - INFO - starting server
2024-12-15 20:43 - INFO - start_recording
2024-12-15 20:43 - INFO - starting recording for test1.mp3
2024-12-15 20:54 - INFO - start_recording
2024-12-15 20:54 - INFO - starting recording for test1.mp3
2024-12-15 20:55 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-15 20:55 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-15 20:55 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 142, in main
KeyboardInterrupt
2024-12-15 20:55 - INFO - starting server
2024-12-15 20:56 - INFO - start_recording
2024-12-15 20:56 - INFO - starting recording for test1.mp3
2024-12-15 20:57 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-15 20:57 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-15 20:57 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 145, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-15 20:58 - INFO - starting server
2024-12-15 20:58 - INFO - start_recording
2024-12-15 20:58 - INFO - starting recording for test1.mp3
2024-12-15 20:59 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-15 20:59 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-15 21:01 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 146, in main
    try:
KeyboardInterrupt
2024-12-15 21:02 - INFO - starting server
2024-12-15 21:02 - INFO - start_recording
2024-12-15 21:02 - INFO - starting recording for test1.mp3
2024-12-15 21:03 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-15 21:03 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-15 21:05 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 147, in main
KeyboardInterrupt
2024-12-15 21:05 - INFO - starting server
2024-12-15 21:07 - INFO - start_recording
2024-12-15 21:07 - INFO - starting recording for gods.mp3
2024-12-15 21:08 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 144, in main
    try:
KeyboardInterrupt
2024-12-15 21:08 - INFO - starting server
2024-12-15 21:09 - INFO - start_recording
2024-12-15 21:09 - INFO - starting recording for gods.mp3
2024-12-15 21:09 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-15 21:09 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-15 21:09 - ERROR - record_stream_data
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 62, in record_stream_data
    if a.value and time.time() < end_time:
TypeError: '<' not supported between instances of 'float' and 'NoneType'
2024-12-15 21:10 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 145, in main
KeyboardInterrupt
2024-12-15 21:11 - INFO - starting server
2024-12-15 21:11 - INFO - start_recording
2024-12-15 21:11 - INFO - starting recording for gods.mp3
2024-12-15 21:11 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-15 21:11 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-15 21:11 - ERROR - record_stream_data
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 65, in record_stream_data
    if a.value and time.time() < end_time:
TypeError: '<' not supported between instances of 'float' and 'NoneType'
2024-12-15 21:11 - INFO - get_recordings
2024-12-15 21:11 - INFO - get_recordings
2024-12-15 21:11 - INFO - get_recordings
2024-12-15 21:11 - INFO - stop_recording
2024-12-15 21:13 - INFO - start_recording
2024-12-15 21:13 - INFO - starting recording for godds2.mp3
2024-12-15 21:13 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-15 21:13 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-15 21:13 - ERROR - record_stream_data
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 65, in record_stream_data
    if a.value and time.time() < end_time:
TypeError: '<' not supported between instances of 'float' and 'NoneType'
2024-12-15 21:15 - INFO - start_recording
2024-12-15 21:15 - INFO - starting recording for test1.mp3
2024-12-15 21:16 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-15 21:16 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-15 21:20 - INFO - start_recording
2024-12-15 21:20 - INFO - starting recording for test1.mp3
2024-12-15 21:20 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 148, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-15 21:20 - INFO - starting server
2024-12-15 21:21 - INFO - start_recording
2024-12-15 21:21 - INFO - starting recording for gods.mp3
2024-12-15 21:21 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-15 21:21 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-15 21:21 - ERROR - record_stream_data
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 65, in record_stream_data
    if a.value and time.time() < end_time:
TypeError: '<' not supported between instances of 'float' and 'NoneType'
2024-12-15 21:21 - INFO - get_recordings
2024-12-15 21:21 - INFO - stop_recording
2024-12-15 21:21 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 148, in main
    data, addr = SOCK.recvfrom(1024)
KeyboardInterrupt
2024-12-15 21:22 - INFO - starting server
2024-12-15 21:22 - INFO - start_recording
2024-12-15 21:22 - INFO - starting recording for gods.mp3.mp3
2024-12-15 21:22 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-15 21:22 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-15 21:22 - ERROR - record_stream_data
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 66, in record_stream_data
    if a.value and time.time() < end_time:
TypeError: '<' not supported between instances of 'float' and 'NoneType'
2024-12-15 21:23 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 149, in main
    print(n.year)
KeyboardInterrupt
2024-12-15 21:23 - INFO - starting server
2024-12-15 21:24 - INFO - start_recording
2024-12-15 21:24 - INFO - starting recording for gods.mp3.mp3
2024-12-15 21:24 - DEBUG - Starting new HTTP connection (1): www.godsdjsradio.com:8080
2024-12-15 21:24 - DEBUG - http://www.godsdjsradio.com:8080 "GET /stream HTTP/1.1" 200 None
2024-12-15 21:24 - INFO - get_recordings
2024-12-15 21:24 - INFO - stop_recording
2024-12-15 21:27 - ERROR - control c
Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 156, in main
    rec.process.join(RUNTIME)
KeyboardInterrupt
2024-12-15 21:27 - INFO - starting server
2024-12-18 13:44 - INFO - start_recording
2024-12-18 13:44 - INFO - starting recording for q.mp4
2024-12-18 13:44 - DEBUG - Starting new HTTP connection (1): hatsubservices.ottc.pro:80
2024-12-18 13:44 - ERROR - record_stream_data
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 446, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marc/.local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 534, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 446, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marc/ffr/ffr_server.py", line 60, in record_stream_data
    response = session.get(url, stream=True)
  File "/home/marc/.local/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/marc/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/marc/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/marc/.local/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
